Serilog:
  
  minimumLevel:

    default: Debug

  MonitoringList: 
    settings-key: RabbitMQMonitoring-MonitoringList
    types:
    - JsonArray

  TelegramToken: 
    settings-key: RabbitMQMonitoring-TelegramToken

  GeneralChatId: 
    settings-key: RabbitMQMonitoring-GeneralChatId
