name: Release Service

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Publish API
      run: dotnet publish --no-build ./src/RabbitStreamMonitoring/RabbitStreamMonitoring.csproj --output ./publish-api --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/}
    - name: Publish API to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/common-rabbit-stream-monitoring
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true